kind: Service
apiVersion: v1
metadata:
  name: nexus-lb
  namespace: nexus
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: scheduler
  ports:
    - port: 8080
      targetPort: 8080