nexus:
  scheduler:
    replicas: 1
    config:
      enabled: true
      cqlStore:
        type: scylla
        secretName: nexus-scylla
scylla:
  datacenter: us-east-1
  racks:
    - name: us-east-1b
      members: 1
      storage:
        capacity: 5Gi
        storageClassName: standard
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
scylla-manager:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  # Scylla instance for Manager
  scylla:
    racks:
      - name: manager-rack
        members: 1
        storage:
          capacity: 2Gi
          storageClassName: standard
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 1
            memory: 512Mi