nexus:
  scheduler:
    replicas: 1
    config:
      enabled: true
      cqlStore:
        type: scylla
        secretRefEnabled: true
        secretName: nexus-scylla
      s3Buffer:
        s3Credentials:
          secretRefEnabled: true
          secretName: nexus-s3
